### ISSUE TITLE
Migrasi Halaman Learning

### ISSUE THREAD

**Issue by yuhanasy** [reactjs-id/website#23]
Migrasi Halaman Learning. Referensi issue #1

**Comment by yuhanasy** [comment]
Minta tolong di _assign_ ya @adibfirman.

**Comment by adibfirman** [comment]
Halo mas @yuhanasy 
kalau boleh tau bagaimana ya progress page ini? Thanks

**Comment by yuhanasy** [comment]
iya maaf mas, baru sempat mengerjakan baru-baru ini, saya sudah buat PR-nya disini #27. 
Monggo di cek dulu mas, thanks

**Comment by adibfirman** [comment]
@yuhanasy siip, nanti agak maleman coba ku cek yaa, thanks banget 👌

**Comment by adibfirman** [comment]
Closed with PR https://github.com/reactjs-id/website/pull/27
