### ISSUE TITLE
add margin-top Footer and remove redundancy background-color PageHeader

### ISSUE THREAD

**Issue by nanto88** [reactjs-id/website#39]
This is a minor issue, may I get to assign PR with this update ?

backgroundImage was doing the same job as backgroundColor, with gradient linear dark grey
[result remove backgroundColor](https://prnt.sc/vajosb)

footer and content in _faq_ maybe need some space between them
[result add mt=24px ](https://prnt.sc/vajp4b)

correct me if I wrong
Thanks in advance

**Comment by adibfirman** [comment]
Hello @nanto88 👋
Thank you for your issue, so at the moment, i think for the `backgroundImage` and `backgroundColor` it's still applicable but for the footer and content in _faq_ page, it was resolved apparently 😅

**Comment by nanto88** [comment]
Okay i don't need to update then , thank you for this response 😄
