### ISSUE TITLE
Migrasi FAQ Page

### ISSUE THREAD

**Issue by muhsatrio** [reactjs-id/website#4]
#1 

@adibfirman

**Comment by adibfirman** [comment]
Halo mas,
Terima sudah mengambil page _FAQ_ ya mas 👌

**Comment by muhsatrio** [comment]
Silahkan cek #10 ya mas @adibfirman terimakasiih

**Comment by adibfirman** [comment]
reference PR https://github.com/reactjs-id/website/pull/10
