### ISSUE TITLE
TopNavigation menumpuk di device =< 520px, kecuali Pixel 2

### ISSUE THREAD

**Issue by EChristian48** [reactjs-id/website#41]
![Screenshot from 2020-10-31 21-29-48](https://user-images.githubusercontent.com/54889298/97781882-ca802a80-1bc0-11eb-8df8-2487118cea71.png)
![Screenshot from 2020-10-31 21-30-03](https://user-images.githubusercontent.com/54889298/97781886-cd7b1b00-1bc0-11eb-99e0-45fa463590d5.png)
![Screenshot from 2020-10-31 21-31-58](https://user-images.githubusercontent.com/54889298/97781887-cf44de80-1bc0-11eb-8610-938f34404c18.png)

Ditest menggunakan Chrome DevTools, Version 86.0.4240.111 (Official Build) (64-bit)

**Comment by muhsatrio** [comment]
Cc: @adibfirman @resir014 @zainfathoni

**Comment by adibfirman** [comment]
thanks for report that mas, mau coba take over ini? biar ku assign mas

**Comment by mnindrazaka** [comment]
Halo mas @muhsatrio @adibfirman 
Saya ingin berkontribusi di issue ini, ini kontribusi pertama saya
Apa saya bisa take over issue ini ?

**Comment by adibfirman** [comment]
@mnindrazaka boleh boleh, ku assign yaa 👌

**Comment by mnindrazaka** [comment]
Halo. Setelah saya periksa, masalahnya adalah item pada menunya tidak muat saat ukuran lebar layar kurang dari 405px.
Berdasarkan masalah tersebut, kita butuh menampilkan layout menu yang berbeda pada breakpoint xs

Ada beberapa solusi yang bisa diterapkan : 

1. Menyembunyikan menu dan menggantinya dengan tombol untuk menampilkan drawer

2. Tetap menampilkan menu namun membuatnya dapat di scroll secara horizontal (seperti pada https://reactjs.org/). Contohnya seperti berikut https://streamable.com/afj1wm

3. Meletakkan logo react di atas, dan semua menunya di bawah. Semacam ini 
<img src="https://user-images.githubusercontent.com/11532800/98437548-97d0b780-2115-11eb-9d60-62293e8882f1.png" width="300" />


Dari beberapa solusi di atas, yang paling sederhana adalah yang nomor 3. Karena merupakan solusi yang paling sederhana dan paling less effort. Apabila menggunakan drawer, jumlah menunya terlalu sedikit, sehingga akan ada banyak white space pada drawernya. Begitu juga dengan scroll, karena menunya hanya 3, maka bagian yang dapat di scroll juga sedikit

Bagaimana menurut teman teman ? @adibfirman @muhsatrio  @EChristian48

**Comment by adibfirman** [comment]
@mnindrazaka halo mas, wah kalo aku sendiri setuju dengan yang nomor 1 atau dengan opsi drawer karena kedepannya kalau menu-nya sudah lebih dari 3 nanti kita kerja 2 kali sih 😅 

kalau nomor 2 agak aneh soalnya gak begitu ngeh kalau menu-nya bisa scrollable gitu sih

**Comment by mnindrazaka** [comment]
@adibfirman berarti ada kemungkinan kalau menunya bakal nambah ya ntar ? oke, kalau pertimbangannya seperti itu, aku juga setuju menggunakan drawer. Aku lanjut implement pake drawer dulu kalau begitu

**Comment by mnindrazaka** [comment]
Aku sudah membuat pull request di link berikut. Mohon reviewnya @adibfirman 
https://github.com/reactjs-id/website/pull/42

**Comment by adibfirman** [comment]
Closed with PR #42
