### ISSUE TITLE
Migrasi Component Header

### ISSUE THREAD

**Issue by SamX23** [reactjs-id/website#6]
#1 
@adibfirman

**Comment by adibfirman** [comment]
Halo mas,
Terima kasih udah mengambil alih ini ya 👏

**Comment by SamX23** [comment]
Mas @adibfirman maaf untuk menampilkan Header di seluruh halaman, ini saya bikinin juga layout indexnya kaya bagian [ini](https://github.com/reactjs-id/reactjs.id/blob/master/src/layouts/index.tsx)  ? atau nunggu yang bagian homepage dan diterapin nanti ?
